### ISSUE TITLE
Where to find the standard T-pose scavenger model?

### ISSUE THREAD

**Issue by BoredBean** [BunyaPineTree/LethalCompany_ModelReplacementSDK#14]
NVM for my last question. I found the solution.

> Additionally, ensure that your model is in a T-pose (rather than A-Pose) with palms facing downwards. Your model's rotation offsets will have a higher fidelity the closer your mode's T-Pose is to the Scavenger's.

After reading this section, I looked for most prefebs and meshes.
But I didn't find one model with a T-pose and hands downwards like in that picture.
Where can I find that standard reference?
Thank you.

**Comment by BoredBean** [comment]
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementSDK/assets/18239170/1c43988e-352e-420a-af98-c5d1debc5cb2)
This is the only one I can find.
But it is not the same pose as you posted on the workflow page.

**Comment by BunyaPineTree** [comment]
The T-posed scavenger is not a standard reference, but rather something I made myself. it's important for the scavenger I use internally to be hands facing downwards, as that is standard practice with model T-poses, and otherwise the fingers get messed up.

**Comment by BoredBean** [comment]
I'm still not sure about this.
As you mentioned before, the closer T-pose the higher fidelity.
So what should I use as reference to modify my model?
Or literally using the letter T?

**Comment by BoredBean** [comment]
I see, you provided a **render preview player** option in the script.
Now it's all clear.
