### ISSUE TITLE
Cannot bundle more than one model per bundle

### ISSUE THREAD

**Issue by emyfops** [BunyaPineTree/LethalCompany_ModelReplacementSDK#8]
Title is self explanatory
Followed the wiki for each model, only builds the first one in the hierarchy

**Comment by emyfops** [comment]
The only way to bundle multiple models is to bundle one, go in the properties of another one, press Build AssetBundle multiple times, click somewhere else and it will add the prefab to the bundle

**Comment by Edouard127** [comment]
Also if I can add something, when I setup model and import them in game, their feet are clipping through the floor, setting the y offset to zero does not fix anything

**Comment by emyfops** [comment]
> The only way to bundle multiple models is to bundle one, go in the properties of another one, press Build AssetBundle multiple times, click somewhere else and it will add the prefab to the bundle
